title: "Rojgar Vacancy"
description: "Rojgar Vacancy is one of the most trusted platforms in India for government job updates, results, admit cards, and recruitment information."
baseurl: ""
url: "https://rojgarvacancy.in"
markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-sitemap
  
